### PR TITLE
Color prompts

### PR DESCRIPTION
**Pull request by eremem**
Add color to the prompt texts during the installation to highlight the need for user's feedback.

### CODE REVIEW

**Comment by Meliox** [comment]
Looks nice with colour prompts!

Using locals for multiple locals makes little sense as they still will be the same local within the same function. Maybe better to use local choice1, choice2 to not accidently have code acting up. Depending on the direction #42 may also be needing corrcetions.

Using upper casing is only for static variables and not something that is set during script runtime, right?
TEMP_UNIT
ENABLE_SYS_INFO

**Review by Meliox — CHANGES_REQUESTED** [review]
Looks nice with colour prompts!

Using locals for multiple locals makes little sense as they still will be the same local within the same function. Maybe better to use local choice1, choice2 to not accidently have code acting up. Depending on the direction https://github.com/Meliox/PVE-mods/pull/42 may also be needing corrcetions.

Using upper casing is only for static variables and not something that is set during script runtime, right?
TEMP_UNIT
ENABLE_SYS_INFO

**Comment by eremem** [comment]
> Using locals for multiple locals makes little sense as they still will be the same local within the same function. Maybe better to use local choice1, choice2 to not accidently have code acting up. Depending on the direction #42 may also be needing corrcetions.

We could rename them to choice\<Subject\>, e.g. choiceTempUnit but I'd still declare them as function's local variables. Otherwise they would "leak" into the global scope which is not desired. The latter is the case for TEMP_UNIT (see below) but it's intended (although not really nice...).

> 
> Using upper casing is only for static variables and not something that is set during script runtime, right? TEMP_UNIT ENABLE_SYS_INFO

Static variables -> global variables ;)

ENABLE_SYS_INFO is indeed a local variable but TEMP_UNIT is global since it's set configure() but used in install_mod(). We could declare it at the beginning but w/o an initial value (because there is none) it would look strange.

**Comment by Meliox** [comment]
Indeed, yes. let's go with _choice_TempUnit, where possible. Maybe TEMP_Unit could be set in the switch case to be consistent?

**Comment by eremem** [comment]
> Indeed, yes. let's go with _choice_TempUnit, where possible. Maybe TEMP_Unit could be set in the switch case to be consistent?

Actually it's ENABLE_SYS_INFO that would need to be camelCased ;) As to TEMP_UNIT, you're right, the user's response should be stored in a local choiceTempUnit variable and the global TEMP_UNIT should be then set in the respective case clause. I'll adjust it so in the next commit.

**Comment by eremem** [comment]
Oh, I see that there is more of those global variables initialized in configure() and used in install_mod() - all of those enableSth...
I'm not quite sure if their names should now all be changed to all caps but this would be consistent (see all these CPU_ in configure()). What do you think?

**Comment by eremem** [comment]
Could you also take a look at the variable enableSensors in install_mod(). It seems that you added this as a part of #47

**Comment by Meliox** [comment]
> Could you also take a look at the variable enableSensors in install_mod(). It seems that you added this as a part of #47

I could move that into to correct sections if any sensor has been enabled if that's what you're hinting?

**Comment by Meliox** [comment]
> Oh, I see that there is more of those global variables initialized in configure() and used in install_mod() - all of those enableSth... I'm not quite sure if their names should now all be changed to all caps but this would be consistent (see all these CPU_ in configure()). What do you think?

For consistency I guess they should be cleaned as well...

**Comment by eremem** [comment]
> > Oh, I see that there is more of those global variables initialized in configure() and used in install_mod() - all of those enableSth... I'm not quite sure if their names should now all be changed to all caps but this would be consistent (see all these CPU_ in configure()). What do you think?
> 
> For consistency I guess they should be cleaned as well...

I think this whole case adjustment should take place in a separate PR and this one focus only on the prompts. I'll take care of it later.

**Comment by eremem** [comment]
> > Could you also take a look at the variable enableSensors in install_mod(). It seems that you added this as a part of #47
> 
> I could move that into to correct sections if any sensor has been enabled if that's what you're hinting?

I'm not sure if we're on the same page. There are 2 variables for sensors:
- *sensorsDetected* used locally in configure(), indicating that there are any sensor readings and 
- *enableSensors* used locally in install_mod() but... once it is set to true, its value never changes and the following *if* compares it against true which is always true... You could just remove the variable and the if clause 😅

**Comment by Meliox** [comment]
> > > Could you also take a look at the variable enableSensors in install_mod(). It seems that you added this as a part of #47
> > 
> > 
> > I could move that into to correct sections if any sensor has been enabled if that's what you're hinting?
> 
> I'm not sure if we're on the same page. There are 2 variables for sensors:
> 
> * _sensorsDetected_ used locally in configure(), indicating that there are any sensor readings and
> * _enableSensors_ used locally in install_mod() but... once it is set to true, its value never changes and the following _if_ compares it against true which is always true... You could just remove the variable and the if clause 😅

Addressed in #59 .

**Comment by eremem** [comment]
@Meliox regarding the core of this PR, is there still anything fundamental that would prevent us from merging? If not, please change the result of your review;)

**Comment by Meliox** [comment]
Sorry. I have addressed all your comments, so I think we can proceed :)

**Review by Meliox — APPROVED** [review]

**Pull request merged**
