### PR TITLE
Temperature unit selection

### PR DESCRIPTION
**Pull request by eremem**
- Extend the setup phase with selection between Celsius and Fahrenheit
- Use `sensors -f` switch for readings in Fahrenheit
- Show an appropriate unit in the node status view

### CODE REVIEW

**Comment by eremem** [comment]
@Meliox could you please check the temperature mod adjustments from this PR? Temperatures seem to be displayed correctly, but when I select Fahrenheit and `sensors -f` is used, the fan speeds also get recalculated and are different from when Celsius was selected.

**Comment by Meliox** [comment]
Sure. Will test later.

**Comment by eremem** [comment]
I think I finally found a possible reason: [lm-sensors #357](https://github.com/lm-sensors/lm-sensors/issues/357). It doesn't seem to be fixed yet...

**Comment by Meliox** [comment]
Good find. I was also planning on looking into their git/code.

**Comment by eremem** [comment]
I implemented my own temperature conversion because the issue with lm sensors is like 1000 years old and no one seems to be willing to fix it. Have a look at the latest version and if you don't see any issues, I'll merge it into the main branch.

**Comment by Meliox** [comment]
Looks good for me.
image

Suggest to rename TempHelper to TempConverter. 

You added quite a lot of conversion check and failure handling. Do you think that's necessary?

**Comment by eremem** [comment]
> 
> Suggest to rename TempHelper to TempConverter.

TempConverter was my first choice too, but I chose Helper as I'm was planning to implement returning the unit itself to make the installer and the code itself a bit simpler.
> 
> You added quite a lot of conversion check and failure handling. Do you think that's necessary?

Yes, I think it's good practice to check input and expect the unexpected (to some extent, of course);D. I don't think this is the part that needs to be "optimized" ;)

**Pull request merged**
