### PR TITLE
Ask user for input for CPU configuration

### PR DESCRIPTION
**Pull request by Meliox**
Disable hdd/ssd information automatically if not found Disable nvme information automatically if not found Remove unintended package install

To accommondate #1 and #3

### CODE REVIEW

**Comment by Meliox** [comment]
Hi @eremem,

Can you check if this also works for you?

**Comment by eremem** [comment]
Hi @Meliox,

I tested the latest version and it seems to work on my system. The step with the configuration does IMHO go in the right direction. I ask myself though, whether it's necessary to ask for the "cpu item prefix". For my Intel CPU it's "Core" but I can't imagine why it should differ for AMD or other brands. What I would ask instead is the CPU temperature input offset, since this could maybe be different for CPU other than Intel.
Apart from this, I had to think twice to understand which parameter being asked is which on the `sensors -j` output;D I think showing an example value (or better offering a default one) would be a good idea for all of the parameters. 

A side note regarding your changes in the JS code: I suppose nobody will actually read the JS code the script adds but me as a developer can barely stand the mix of camelCase and snake_case for the variable/constant names (I mean the resulting JS code only, not the bash variables):D. Would you please consider tidy this up?:D

**Comment by eremem** [comment]
Oh, I see now where the idea behing the CPU configuration comes from (https://github.com/Meliox/PVE-mods/issues/1#issuecomment-1610885106). What lm-sensors return for an AMD CPU is... "fascinating" :D I guess, this makes my "brilliant" idea about leaving "Core" as-is useless:/

**Comment by Meliox** [comment]
Hi @eremem

Thanks for the review and comments. Asking about configuration was an idea I wanted to try because its more flexible and because Amd is very different. Both in naming, but also index of the cores. See below. 

Ideally I wanted something that the user should not have to edit, but I have no idea of what it will look like on Epyc, xeons etc. Maybe guide the user more? Bash though has no inbuilt json parser, that requires a package to be installed, eg. to present it nicer with selections. Another way could be of making an array with a known list and see if one of those I being used? I am very open for ideas. 

Do we have examples where temp offset is used? Can you share sensor - j from your system? 

You're absolutely right about code quality. Its not consistent and for JS i am into new territories with help of openai and that one should be told exactly what to do :D

I will improve the quality once a direction is set. 

AMD
{
   "nvme-pci-0100":{
      "Adapter": "PCI adapter",
      "Composite":{
         "temp1_input": 36.850,
         "temp1_max": 81.850,
         "temp1_min": -273.150,
         "temp1_crit": 84.850,
         "temp1_alarm": 0.000
      },
      "Sensor 1":{
         "temp2_input": 36.850,
         "temp2_max": 65261.850,
         "temp2_min": -273.150
      },
      "Sensor 2":{
         "temp3_input": 41.850,
         "temp3_max": 65261.850,
         "temp3_min": -273.150
      }
   },
   "k10temp-pci-00c3":{
      "Adapter": "PCI adapter",
      "Tctl":{
         "temp1_input": 51.625
      },
      "Tccd1":{
         "temp3_input": 48.750
      },
      "Tccd2":{
         "temp4_input": 45.000
      }
   }
}

**Comment by eremem** [comment]
Such a "database" for different CPUs is not a bad idea. Having some lm-sensors outputs for different CPU brands and maybe for different models of each manufacturer would be helpful for looking for a possible patterns. The idea with a "database" is good regardless of the result of the analysis for different CPU brands - ideally if some patterns in sensor paths could be found, the number of "records" in this "database" could be smaller, but you could skip asking for the sensor path when matching one is found.

My output for an 10th generation Intel i7 looks like this (I removed the irrelevant parts):
```
   "coretemp-isa-0000":{
      "Adapter": "ISA adapter",
      "Package id 0":{
         "temp1_input": 36.000,
         "temp1_max": 82.000,
         "temp1_crit": 100.000,
         "temp1_crit_alarm": 0.000
      },
      "Core 0":{
         "temp2_input": 35.000,
         "temp2_max": 82.000,
         "temp2_crit": 100.000,
         "temp2_crit_alarm": 0.000
      },
      "Core 1":{
         "temp3_input": 34.000,
         "temp3_max": 82.000,
         "temp3_crit": 100.000,
         "temp3_crit_alarm": 0.000
      },
      "Core 2":{
         "temp4_input": 35.000,
         "temp4_max": 82.000,
         "temp4_crit": 100.000,
         "temp4_crit_alarm": 0.000
      },
      "Core 3":{
         "temp5_input": 34.000,
         "temp5_max": 82.000,
         "temp5_crit": 100.000,
         "temp5_crit_alarm": 0.000
      },
      "Core 4":{
         "temp6_input": 34.000,
         "temp6_max": 82.000,
         "temp6_crit": 100.000,
         "temp6_crit_alarm": 0.000
      },
      "Core 5":{
         "temp7_input": 34.000,
         "temp7_max": 82.000,
         "temp7_crit": 100.000,
         "temp7_crit_alarm": 0.000
      },
      "Core 6":{
         "temp8_input": 35.000,
         "temp8_max": 82.000,
         "temp8_crit": 100.000,
         "temp8_crit_alarm": 0.000
      },
      "Core 7":{
         "temp9_input": 35.000,
         "temp9_max": 82.000,
         "temp9_crit": 100.000,
         "temp9_crit_alarm": 0.000
      }
   },

```
As far as parsing JSON there is e.g. `jq` but as you mentioned - it had to be installed from a package first, adding a dependency to the script.

**Comment by Meliox** [comment]
I added some logic for that now. Should work for Intel and AMD system I have data on. The logic is not pretty - bash is to blame.

Do you still need the core offset?

The naming of variable is also consistent now ;)

**Comment by eremem** [comment]
> 
> Do you still need the core offset?
> 
It seems that the constant is not used anymore in the last version. I'll have to check the JS code, because now e.g. this line:
`coreKeys = Object.keys(items).filter(item => \{ return String(item).includes(cpuItemPrefix); \}).sort();\n\\n\`
doesn't seem to be doing what I originally meant it to:D. Additionally I spotted a few declarations missing const/let.

**Comment by evoandroidevo** [comment]
Sorry about the long wait just got a chance to test and it doesn't work for me still

image
image

**Comment by eremem** [comment]
@Meliox I made a bunch of changes to your latest commit but I couldn't find a way how I should push it to you now. This branch of yours is read-only for me and it seems that I can't make a PR from it either.
The only thing I came up with would be pushing my changes to my repository to make them generally available to the outer world but this seems somehow counterintuitive to me in this case... and I don't really want these changes in my (master) branch yet:/.
Any idea how it works here?

**Comment by eremem** [comment]
@Meliox OK, thanks for the invitation:) I pushed the changes now.

**Comment by eremem** [comment]
@evoandroidevo Could you please check if the latest version works for you now?

**Comment by Meliox** [comment]
You only changed the prefix for AMD?

Den søn. 2. jul. 2023 kl. 16.42 skrev eremem ***@***.***>:

**Comment by eremem** [comment]
> Looks good. More a less a complete rewrite and looks pretty :) 
I know the diff looks a little "scary" but this is mostly due to the multiple smaller changes.

> You only changed the prefix for AMD?
Yes, but I also added a configurable caption which will be shown in the summary (as it was with "Core X" before). Since the temperatures for the AMD CPUs are not provided per core, it makes more sense to me to be able to treat them in a generic way. And you don't have to stick to a single value only.

**Comment by eremem** [comment]
I've always used sed for very simple replacements. You may have noticed my comment in the code:
`# NOTE: The following items will be added in reverse order`
I had to reverse the order in which the JS code snippets for NVMe and HDD/SDD are injected, because I couldn't set the sed's "lookup address" right for them (please also note the change to the property `ItemId` in the JS code) and otherwise the NVMe section landed below the one with the HDD/SDD temps.
Do you have an idea how the affected sed calls could be improved? The solution must take into account that individual sections are optional depending on the available sensors. To be honest, I haven't been able to test this use case more thoroughly...

**Comment by Meliox** [comment]
Hmm. Maybe use the specific key that is unique to each section? E.g. "thermalNvme" and then handle it the optionals with if/else. I can't see a pretty way to make it in a flexible manner. I was actually more thinking if it could be flexible in the js part. If no sensor is available content/section is not N/A is just empty.

**Comment by evoandroidevo** [comment]
it shows CPU temps for me now thanks for the awesome work
image

**Comment by Meliox** [comment]
But is that correct for AMD? Temp 0 and 1 are the actual temps and temp 2 is one with an offset to work with fans: https://www.reddit.com/r/Amd/comments/f21cjx/whats_the_difference_between_cpu_tctltdie_and_cpu/

Imo, temp2 is not really meaningful, yet i'll let you decide?

**Comment by eremem** [comment]
@Meliox It seems to me that it's smarter to avoid injecting JS code if the sensors couldn't be detected (more or less as you implemented it). The problem with anchors like "thermalNvme" or "thermalHdd" is that you had to always consider the both cases where the section will be visible or not. A kind of priority list with the itemIds comes to my mind but whether it's doable with sed?

**Comment by evoandroidevo** [comment]
> But is that correct for AMD? Temp 0 and 1 are the actual temps and temp 2 is one with an offset to work with fans: https://www.reddit.com/r/Amd/comments/f21cjx/whats_the_difference_between_cpu_tctltdie_and_cpu/
> 
> Imo, temp2 is not really meaningful, yet i'll let you decide?

I would swap tctl to temp 0 or remove it. The ccd temps are the ones that matter since they have cpu cores themselves

**Comment by Meliox** [comment]
> @Meliox It seems to me that it's smarter to avoid injecting JS code if the sensors couldn't be detected (more or less as you implemented it). The problem with anchors like "thermalNvme" or "thermalHdd" is that you had to always consider the both cases where the section will be visible or not. A kind of priority list with the itemIds comes to my mind but whether it's doable with sed?

Sed cannot do that. You would have awk or sort to make such a list prior to do sed.

**Comment by eremem** [comment]
What we could do now just by changing the default configuration is to limit the display either to Tctl only or to both values for Tccd.

**Comment by Meliox** [comment]
@eremem Some more data available here #5 with a couple of things that we need to look into.

Should we consider extrating the correct core id instead of adding one ourselves?

Something is wrong in the NVME JS as only one drive is showing up. Will have a look tomorrow.

**Comment by eremem** [comment]
> Should we consider extrating the correct core id instead of adding one ourselves?

I don't think it would be a good idea. This way you would see those gaps in the internal core indexing. What should it be good for? It would look like some temperatures are missing.
The problem with the mismatching order of the temperatures between the `sensors -j` output and the summary panel is caused by the sorting algorithm - we get "Core 0", "Core 10", "Core 11", ..., "Core 15", "Core 4", "Core 8", "Core 9". I'll have to change it, so that the indices are compared. This is not so obvious though, since, at least in theory, the prefixes could vary (as it would be possible for the AMD sensors) and then we would compare apples with pears.

> Something is wrong in the NVME JS as only one drive is showing up. Will have a look tomorrow.

Am I missing something? There is only one item for a NVMe drive (nvme-pci-0100). The JS code takes the input from the "Composite" sensor. Your initial implementation also worked this way as far as I remember.

**Comment by Meliox** [comment]
You're right about that, there would be a gap. However, that is how the data is read and presented and thus if you look in any other program they would be the same=coherence I assume? 
I agree that the approach is not straight forward. I do like removal of the sorting. All examples I have seen are sorted properly by default.?

NVME: correct. Let's leave it at that.

**Comment by eremem** [comment]
Yes, from what I can tell, the CPU temperatures were always returned in the right order, making the sorting redundant.

**Comment by Meliox** [comment]
Also remove sorting for nvme and hdd to make it consistent? Maybe not a huge problem as the number of user having that many is not many...

**Comment by eremem** [comment]
> Also remove sorting for nvme and hdd to make it consistent? Maybe not a huge problem as the number of user having that many is not many...

No I left sorting for the drives. Their sensors' output is a real mess on my system when it comes to the order there but when sorted by their addresses the drives seem to match the order of /dev/sd*, so it's also easy to compare the temperatures shown on the summary panel and those from the S.M.A.R.T data.

**Comment by Meliox** [comment]
Found this example of 2 NVMe's:
`nvme-pci-0100
Adapter: PCI adapter
Composite:    +46.9°C  (low  =  -0.1°C, high = +83.8°C)
                       (crit = +87.8°C)
Sensor 1:     +60.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +46.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +110.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +33.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +33.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +33.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +33.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +33.0°C  (high = +105.0°C, crit = +105.0°C)

nvme-pci-0600
Adapter: PCI adapter
Composite:    +45.9°C  (low  = -273.1°C, high = +84.8°C)
                       (crit = +84.8°C)
Sensor 1:     +45.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +46.9°C  (low  = -273.1°C, high = +65261.8°C)`

We only have the address number as "index". We could show that, or leave it as 1 and 2.

**Comment by eremem** [comment]
> We only have the address number as "index". We could show that, or leave it as 1 and 2.

So we would either have "Disk 0100" and "Disk 0600" or we would change the current indexing from 0 and start from 1?
I'm not convinced that we would gain anything with any of these changes. What would be your motivation and which variant (if any) would you prefer?

**Comment by Meliox** [comment]
I don't think we would gain anything either, thus I would stay with 1, 2, n... to keep it simple and clean.

**Comment by eremem** [comment]
I just noticed, that there are 2 exits in uninstall_mod() when no backup file(s) are found. This makes calling the script with both parameters specified impossible. The use case is that one wants to restore the original files before applying the modifications from the latest script version, like so:  `./pve-mod-gui-temp.sh uninstall install.`
Obviously this works correctly as long as the restore logic remains unchanged but it's actually mostly the case.
What do you think, could we remove these two `exit 1` called after printing a warning?

**Comment by Meliox** [comment]
> I just noticed, that there are 2 exits in uninstall_mod() when no backup file(s) are found. This makes calling the script with both parameters specified impossible. The use case is that one wants to restore the original files before applying the modifications from the latest script version, like so: `./pve-mod-gui-temp.sh uninstall install.` Obviously this works correctly as long as the restore logic remains unchanged but it's actually mostly the case. What do you think, could we remove these two `exit 1` called after printing a warning?

Scenario 1: pveproxy is updated from proxmox side. Install instruction would be "install".
Scenario 2: The mod script is updated. Install instruction would be "uninstall, install"
Scenario 3: If already installed, then it cannot be installed before old changes have been removed: https://github.com/Meliox/PVE-mods/blob/5f3cefaca040e200f4678442ae9af1999b3a7c5a/pve-mod-gui-temp.sh#L169 https://github.com/Meliox/PVE-mods/blob/5f3cefaca040e200f4678442ae9af1999b3a7c5a/pve-mod-gui-temp.sh#L181. Original file from proxmox must first be installed.

I do not see a reason not to be able to remove to exists and leave the warnings. I will remove them a merge the changes :)

**Pull request merged**
