### PR TITLE
add support multiple Fan Speed Key Patterns

### PR DESCRIPTION
**Pull request by Meliox**
Implement #41 

Example 1:
```
{
   "asus_wmi_sensors-virtual-0": {
      "Adapter": "Virtual device",
      "CPU Core Voltage": {
         "in0_input": 0.970
      },
      "+12V Voltage": {
         "in1_input": 12.230
      },
      "+5V Voltage": {
         "in2_input": 4.960
      },
      "3VSB Voltage": {
         "in3_input": 3.314
      },
      "CPU Fan": {
         "fan1_input": 1451.000
      },
      "Chassis Fan 1": {
         "fan2_input": 1527.000
      },
      "Chassis Fan 2": {
         "fan3_input": 1486.000
      },
      "Chassis Fan 3": {
         "fan4_input": 1477.000
      },
      "AIO Pump": {
         "fan5_input": 0.000
      },
      "Water Pump": {
         "fan6_input": 0.000
      },
      "CPU OPT": {
         "fan7_input": 0.000
      },
      "CPU Temperature": {
         "temp1_input": 42.000
      },
      "Motherboard Temperature": {
         "temp2_input": 30.000
      },
      "Chipset Temperature": {
         "temp3_input": 44.000
      },
      "Tsensor 1 Temperature": {
         "temp4_input": 216.000
      }
   },
   ...
}
```

Example 2:

```
{
   "coretemp-isa-0000": {
      "Adapter": "ISA adapter",
      "Package id 0": {
         "temp1_input": 44.000,
         "temp1_max": 105.000,
         "temp1_crit": 105.000,
         "temp1_crit_alarm": 0.000
      },
      "Core 0": {
         "temp2_input": 41.000,
         "temp2_max": 105.000,
         "temp2_crit": 105.000,
         "temp2_crit_alarm": 0.000
      },
      "Core 1": {
         "temp3_input": 41.000,
         "temp3_max": 105.000,
         "temp3_crit": 105.000,
         "temp3_crit_alarm": 0.000
      },
      ...
   },
   "it8620-isa-0a20": {
      "Adapter": "ISA adapter",
      ...
      "fan2": {
         "fan2_input": 0.000,
         "fan2_min": 47.000,
         "fan2_alarm": 1.000,
         "fan2_beep": 0.000
      },
      "fan3": {
         "fan3_input": 1112.000,
         "fan3_min": 12.000,
         "fan3_alarm": 0.000,
         "fan3_beep": 0.000
      },
      ...
   },
   ...
}
```

Result (active fans only):
image

Result (all, e.g. idle fans and non configured as well. last mentioned must be disabled in sensors if you don't want them):
image

### CODE REVIEW

**Comment by Meliox** [comment]
@eremem: It's ready for review.. Not sure if you got the notification. Thanks

**Review by eremem — COMMENTED** [review]
All of my fans spin, so I couldn't verify this case. I assume with a proper dump file it worked, didn't it?). But for my system, the readings look good:
obraz

The fan captions are the capitalized "IDs" from the `sensors` output.

**Comment by Meliox** [comment]
It did work yes (example 1) in OP.

I decided to capitalize them? Do you prefer to leave them unedited?

**Comment by eremem** [comment]
I think this letter case change is OK, otherwise I had fan1: ..., | fan2: ... etc. which doesn't really look good.

**Comment by Meliox** [comment]
My thought as well :)

**Comment by eremem** [comment]
I installed the current version from the main branch on a system with 1 "idle" fan and disabled displaying stopped fans:
obraz

Still I can see the affected fan in the frontend:
obraz

(browser cache was cleared)

Here is a dump file from that system: 
[sensorsdata.json](https://github.com/user-attachments/files/15865034/sensorsdata.json)

**Comment by eremem** [comment]
`read` assigns the response to the variable passed as a 2nd parameter. 
The line `+ local choiceDisplayZeroSpeedFans=` implies that the return value of `$(read ...)` is `""` and this matches the case `[yY]|""`, so displayZeroSpeedFans=true.

As long as we can't use the `ask` function for user prompts (#56), the line:
`local choiceDisplayZeroSpeedFans=$(read -p "Do you wish to display fans reporting a speed of zero? If no, only active fans will be displayed. (Y/n)")`

should be replaced by:
`read -p "Do you wish to display fans reporting a speed of zero? If no, only active fans will be displayed. (Y/n)" choiceDisplayZeroSpeedFans`

**Comment by Meliox** [comment]
I see. Thanks for the explanation. I'll have it fixed tomorrow.

**Pull request merged**
