### PR TITLE
save-sensors-data argument

### PR DESCRIPTION
**Pull request by Meliox**
Add an argument to save sensors data, so that it can be shared.

### CODE REVIEW

**Review by eremem — CHANGES_REQUESTED** [review]
Nice idea!

Have a look at my patch: 
[0001-Reuse-global-path-variables-make-small-adjustments.patch](https://github.com/user-attachments/files/15853649/0001-Reuse-global-path-variables-make-small-adjustments.patch)


For the script's path there is already a global variable `SCRIPT_CWD`, so there is no need for a local one. I would also add an another global variable: `DEBUG_DUMP_DIR`. 

It could also be a good idea to declare the dump file name and its path globally instead of doing it locally in the function. Such a global configuration would make any further adjustments easier. The dump file name declared globally could be then reused as expected file name for the debug mode. That's why I'd suggest to declare both: the dump file name and its path as 2 global variables. These are not in the patch file though.

**Comment by Meliox** [comment]
Cool. Good idea. I made the changes and add a check for the path as well.

You had to cosmetic changes, I'll leave those for another PR to keep it clean.

**Comment by eremem** [comment]
> Cool. Good idea. I made the changes and add a check for the path as well.
> 
> You added some cosmetic changes, I'll leave those for another PR to keep it clean.

For the formatting I use the *shell-format* VS Code addon. You can trigger it with the usual shortcut (alt+shift+f) for the edited file and it does a decent job.

**Comment by Meliox** [comment]
I think you have to approve the changes for the 2 PRs before I can merge them.

**Review by eremem — APPROVED** [review]

**Comment by eremem** [comment]
Done

**Pull request merged**
